server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:33066/my_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.zbl.springboot.dao: debug
